### ISSUE TITLE
It will delete some comments

### ISSUE THREAD

**Issue by KerwinChen** [morganestes/sublime-recess#11]
It delete some personal comments between {...} .
such as

```
.element {
    background: #011027;
    background: rgba(1, 16, 39, 0.5) !important;
    /*-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=60)"; /* ie8  */
    filter: alpha(opacity=50);
    /* ie5-7  */
    /*opacity: 0.5; /* css standard, currently it works in most modern browsers  */
}
```

**Comment by morganestes** [comment]
Sorry that's happening to you. You can help me find out more by answering a couple of questions:
1. What's the output you're getting when you compile this code (which comments are stripped)?
2. What versions of `recess` and `node` are you running? You can check with `recess --version` and `node --version`.

**Comment by morganestes** [comment]
When I compile the code you presented above with the default settings, I get this:

``` css
.element {
  background: #011027;
  background: rgba(1, 16, 39, 0.5) !important;
  /*-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=60)"; /* ie8  */

  filter: alpha(opacity=50);
  /* ie5-7  */

  /*opacity: 0.5; /* css standard, currently it works in most modern browsers  */

}
```

The comments are only stripped out when I add the extra setting to compress:

``` css
.element{background:#011027;background:rgba(1,16,39,0.5)!important;filter:alpha(opacity=50)}
```
